import com.ftn.sbnz.model.Client;
import com.ftn.sbnz.enumeration.Category
import com.ftn.sbnz.model.Transaction;
import com.ftn.sbnz.model.Warning;
import java.util.Calendar;
import java.sql.Timestamp;
import java.util.List;


// rule "Generate Mild Warning for Excessive Spending"
//     when
//         $client: Client($clientId: id)
//         $currentMonthIncome: Number(doubleValue > 0) from accumulate(
//             $t1: Transaction(
//                 clientId == $clientId, 
//                 type == Transaction.Type.INCOME, 
//                 date >= startOfMonth(), 
//                 date <= today()), 
//             sum($t1.getValue())
//         )
//         // $category: Category()
//         $transactions: List() from accumulate(
//             Transaction(clientId == $clientId, category == Category.SHOPPING, value > 0, date >= startOfMonth(), date <= today()), // Add date condition to filter transactions for the current month
//             collectList()
//         )
//         $totalSpending: Number(doubleValue > 0) from accumulate(
//             $t3: Transaction(clientId == $clientId, category == Category.SHOPPING, value > 0, date >= startOfMonth(), date <= today()), 
//             sum($t3.getValue())
//         )
//         eval($transactions.size() >= 3)
//         eval($totalSpending.doubleValue() > ($currentMonthIncome.doubleValue() * 0.1))
//     then
//         System.out.println("Mild warning generated for client " + $transactions.size());
//         insert(new Warning($clientId, "Mild", "You have spent more than 10% of your monthly income on SHOPPING."));
//         // String categoryName = $category.name();
//         System.out.println("Mild warning generated for client " + $clientId + " in category ");
// end

// Utility functions to get start of the current month and current day
function Timestamp startOfMonth() {
    Calendar cal = Calendar.getInstance();
    cal.set(Calendar.DAY_OF_MONTH, 1);
    cal.set(Calendar.HOUR_OF_DAY, 0);
    cal.set(Calendar.MINUTE, 0);
    cal.set(Calendar.SECOND, 0);
    cal.set(Calendar.MILLISECOND, 0);
    return new Timestamp(cal.getTimeInMillis());
}

function Timestamp today() {
    Calendar cal = Calendar.getInstance();
    cal.set(Calendar.HOUR_OF_DAY, 23);
    cal.set(Calendar.MINUTE, 59);
    cal.set(Calendar.SECOND, 59);
    cal.set(Calendar.MILLISECOND, 999);
    return new Timestamp(cal.getTimeInMillis());
}

// 1. LEVEL

rule "Set Flag for 3 Purchases in a Category"
    when
        $client: Client($clientId: id)
        $category: Category() from Category.values() 
        $transactions: List(size >= 3) from accumulate(
            Transaction(clientId == $clientId, category == $category, value > 0, date >= startOfMonth(), date <= today()), 
            collectList()
        )
    then
        modify($client) {
            setThreePurchases(true)
        }
        System.out.println("Flag ThreePurchases set for client " + $clientId + " in category " + $category.name());
end


rule "Set Flag for 5 Purchases in a Category"
    when
        $client: Client($clientId: id)
        $category: Category() from Category.values() 
        $transactions: List(size >= 5) from accumulate(
            Transaction(clientId == $clientId, category == $category, value > 0, date >= startOfMonth(), date <= today()), 
            collectList()
        )
    then
        modify($client) {
            setFivePurchases(true)
        }
        System.out.println("Flag FivePurchases set for client " + $clientId + " in category " + $category.name());
end


// 2. LEVEL

rule "Set Flag3 if Flag1 and Spending > 10% Income"
    when
        $client: Client($clientId: id, threePurchases == true, flag3 == false)
        $currentMonthIncome: Number(doubleValue > 0) from accumulate(
            $income: Transaction(clientId == $clientId, type == Transaction.Type.INCOME, date >= startOfMonth(), date <= today()), 
            sum($income.getValue())
        )
        $totalSpending: Number(doubleValue > 0) from accumulate(
            $expense: Transaction(clientId == $clientId, value > 0, date >= startOfMonth(), date <= today()), 
            sum($expense.getValue())
        )
        eval($totalSpending.doubleValue() > ($currentMonthIncome.doubleValue() * 0.1))
    then
        modify($client) {
            setFlag3(true)
        }
        System.out.println("Flag3 set for client " + $clientId + " as spending exceeds 10% of income");
end


rule "Set Flag4 if Flag2 and Spending > 25% Income"
    when
        $client: Client($clientId: id, fivePurchases == true, flag4 == false)
        $currentMonthIncome: Number(doubleValue > 0) from accumulate(
            $income: Transaction(clientId == $clientId, type == Transaction.Type.INCOME, date >= startOfMonth(), date <= today()), 
            sum($income.getValue())
        )
        $totalSpending: Number(doubleValue > 0) from accumulate(
            $expense: Transaction(clientId == $clientId, value > 0, date >= startOfMonth(), date <= today()), 
            sum($expense.getValue())
        )
        eval($totalSpending.doubleValue() > ($currentMonthIncome.doubleValue() * 0.25))
    then
        modify($client) {
            setFlag4(true)
        }
        System.out.println("Flag4 set for client " + $clientId + " as spending exceeds 25% of income");
end

// 3 LEVEL
rule "Generate Mild Warning for Flag3"
    when
        $client: Client($clientId: id, flag3 == true)
    then
        insert(new Warning($clientId, "Mild", "You have spent more than 10% of your monthly income."));
        System.out.println("Mild warning generated for client " + $clientId);
end


rule "Generate High Warning for Flag4"
    when
        $client: Client($clientId: id, flag4 == true)
    then
        insert(new Warning($clientId, "High", "You have spent more than 25% of your monthly income."));
        System.out.println("High warning generated for client " + $clientId);
end
