import com.ftn.sbnz.model.Transaction;
import com.ftn.sbnz.model.CreditCard;


rule "Update current balance"
when
    $transaction: Transaction($type: type, $value: value, $clientId: clientId)
    $card: CreditCard(clientId == $clientId)
then
    System.out.println("Promjena stanja na kartici");
    double newBalance = 0;
    if ($type == Transaction.Type.INCOME) {
        newBalance = $card.getBalance() + $value;
    }
    else {
        newBalance = $card.getBalance() - $value;
    }
    System.out.println(Double.toString(newBalance));
    modify($card){setBalance(newBalance);}
end

