import com.ftn.sbnz.model.Transaction;
import com.ftn.sbnz.model.CreditCard;


rule "New transaction added - update current balance"
when
    $transaction: Transaction($type: type, $value: value, $clientId: clientId)
    $card: CreditCard(clientId == $clientId)
then
    if ($type == Transaction.Type.INCOME) {
        $card.setBalance($card.getBalance() + $value);
    }
    else {
        $card.setBalance($card.getBalance() - $value);
    }
    update($card);
end
